### ISSUE TITLE
Would you please put the OCamCalib src in the repositary?

### ISSUE THREAD

**Issue by yourwanghao** [urbste/ImprovedOcamCalib#1]
I have some problem that I can't download the original OCamCalib from google, so would you please put the source in this repo that I can clone?

Thanks!

**Comment by urbste** [comment]
The improved code will be released soon. Just got the corresponding paper in the review pipeline.
You can download the original source code from the authors website: http://rpg.ifi.uzh.ch/software/ocamcalib/Scaramuzza_OCamCalib_v3.0_win.zip
Cheers
